FROM python:3.5.3

# MAINTAINER is deprecated. Use LABEL instead.
LABEL maintainer "Qian Liu <liu.qian.am@gmail.com>"

# Install nginx, supervisor
RUN apt-get update --fix-missing
        && apt-get install -y nginx supervisor

# Stop nginx and supervisor
RUN service supervisor stop \
        && service nginx stop

# create virtual env with with python3.5.3 in /opt/venv
RUN pip install virtualenv
RUN virtualenv  /opt/venv
ADD ./requirements.txt /opt/venv/requirements.txt
RUN /opt/venv/bin/pip install -r /opt/venv/requirements.txt

# expose port
EXPOSE 8081 9002

RUN pip install supervisor-stdout

# Add our config files
ADD ./supervisor.conf /etc/supervisor.conf
ADD ./nginx.conf /etc/nginx/nginx.conf

# Copy our service code
ADD ./transform-service /opt/transform_service

# start supervisor to run our wsgi server, nginx, supervisor-stdout
CMD supervisord -c /etc/supervisor.conf -n
